name: discord_logger
description: A simple flutter package to send message to discord channel via discord bot
version: 1.0.0
homepage: https://github.com/slimpotatoboy/discord_logger

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.5